title: Bits & Bytes – Home Lab
description: Notes, designs, guides, and templates from my home lab journey.
url: https://www.bitsandbytes.co.uk
baseurl: ""

# Tell Jekyll that your source folder is /docs
source: docs

# Use the Just the Docs theme via remote_theme (works with GitHub Pages)
remote_theme: just-the-docs/just-the-docs@v0.10.1
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
  # - jekyll-scholar
  # - jekyll-redirect-from
  # - jekyll-archives

just_the_docs:
  search_enabled: true
  nav_enabled: true
  collections:
    guides:
      name: Guides
      nav_fold: true
    designs:
      name: Designs
      nav_fold: true
    runbooks:
      name: Runbooks
      nav_fold: true
    templates:
      name: Templates
      nav_fold: true
    notes:
      name: Notes
      nav_fold: true

# Header (top-right) links
aux_links:
  "GitHub Repo":
    - "https://github.com/BKOmega/BKOmega.github.io"
aux_links_new_tab: true   # open header links in a new tab


# (Optional) External links in the left nav (if you add any there)
# nav_external_links:
#   - title: "My External Thing"
#     url: "https://example.com"
nav_external_links_new_tab: true

# Collections
collections:
  guides:
    output: true
    permalink: /guides/:path/
  designs:
    output: true
    permalink: /designs/:path/
  runbooks:
    output: true
    permalink: /runbooks/:path/
  templates:
    output: true
    permalink: /templates/:path/
  notes:
    output: true
    permalink: /notes/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
      toc: true
      badges: []
      tags: []
      last_tested: 2025-10-29

# Include custom head for scripts/styles
include:
  - _includes/head_custom.html
  - assets/js/copy.js
  - assets/css/custom.scss

logo: /assets/img/social-card.png